### ISSUE TITLE
DSCI 532 Peer Review

### ISSUE THREAD

**Issue by j99thoms** [j99thoms/smash-charts#8]
Thoughts on the Dashboard?

I value any feedback, input, or bug reports you might have.

**Comment by samson-bakos** [comment]
This is a super creative concept!

My only feedback points are very minor adjustments:

* Possibly display units on the axis labels for the various plots since speeds/ accelerations in frames/ game distance units is non intuitive for people not versed in how Smash works
* Move up the right bar chart to be in line with the scatter plot

(Not actually feedback): 
* Missed opportunity to call this "SuperSmashBoard"

**Comment by ChesterAiGo** [comment]
Great app Jakob I like it very much :)
It's evident that it's designed for Super Smash Bros players, and as one myself, I found it intriguing to view the statistics of our favourite characters in the game. The app is quite user-friendly as well.

Some suggestions for potential future improvements:

- Instead of using dots in the scatter plot, consider using mini character icons. This could make the visuals more intuitive and easier to interpret.
- As a personal design preference, I would recommend dividing the content into two separate pages.

Overall great app Jakob!

**Comment by austin-shih** [comment]
Super cool tool! 
- I can understand why I was so bad at Super Smash Bros now...
- I really like how you explained all the attributes, makes the visualization more understandable.
- I like how this app is very user friendly and easy to use. 
- for future development, could create profile of characters and do comparisons.
